language: go

# https://github.com/travis-ci/travis-ci/issues/2517
matrix:
  allow_failures:
    - go: master
  include:
    - env: GO111MODULE=on GOOS_=linux GOARCH_=amd64
      go: stable
    - env: GO111MODULE=on GOOS_=linux GOARCH_=arm GOARM_=6
      go: stable
    - env: GO111MODULE=on GOOS_=linux GOARCH_=arm GOARM_=7
      go: stable
    # Test other Go versions
    - env: GO111MODULE=on GOOS_=linux GOARCH_=amd64
      go: master

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq mpd mpc
  - go get -u golang.org/x/lint/golint
  - ./just install

before_script:
  - sudo cp -r $TRAVIS_BUILD_DIR/testdata $(sudo sed -n 's/^music_directory\s\+"\(.\+\)"/\1/p' /etc/mpd.conf)
  - echo -e '\n
      max_connections "100"\n
      audio_output {\n
          type "null"\n
          name "My Null Output"\n
          mixer_type "software"\n
      }' | sudo tee -a /etc/mpd.conf
  - sudo service mpd restart
  - mpc update --wait
script:
  - gofmt -s -d ./src/
  - ./just build
  - RELEASE=1 ./just build
  - go test -test.v -race ./src/...
  - go vet ./src/...
  - golint -set_exit_status -min_confidence 0.3 ./src/...

before_deploy:
  - GOOS=$GOOS_ GOARCH=$GOARCH_ GOARM=$GOARM_ bash ci/before_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: TNCBWt6FUCx1YYoG+hjkB83GOA0C+le5QiU5t5BfOBBD6UYeMTAo5Vezj7NbZ8ggNPIPm2aD0KrKoX3MoNq4n2dswCcRPXsgwDFLjSvXEqEVxyF14Wxq6onKbxa6MdA4gMarNVmcj6Odsa/4btlqe5vn9ubu54Z1QW1JQRm/IoqYQUuKMqydxKFGXQTxCvLGX/92cKRhQ4Kv3dWPLLRjvNg6uv0I1woH//n/81IpnasTDX21XtlgHk1dcRETYznOMeHPTnuRB8KJUm31wV/UZezGeUD/fK61sGr8sqvpwD/84ldU9GttNGd2q/WIFsKEQ08t6YBTgrjGsfnOyv8m2r9pLazQRtZ/2iabfvlCLVSEHBfSQf6+2wTSq2AVDHltmawUHjmq9lDdMsLy7LTWatN1yyyAan/CHwzxC2rvVqfx+D6i5T0iU2CmtsOrP1A99lw7oypurwTcqBOGofj6oU+XofJUViX14WjGwfH8fdOmL/Za8cUQgddJsg5cniziXV6Oj4ejEHebh7QZywTHKGXGRDmyp2DIHD4/ETtE5Pv7R6cDpJ76TaNgEw92/SWmAz97HDaHk7mV1XtgcCAKyaiP9VhjfhScUOvPYaq7qGPJAdxXGGUdrzQ44Pu1fTNpAWkbXJcAIr85sAORO6QMFD6ayjrpxBD0UE3lNj9uoK4=
  file_glob: true
  file: "trollibox-$TRAVIS_TAG*.tar.gz"
  skip_cleanup: true
  on:
    condition: $TRAVIS_GO_VERSION = stable
    tags: true

notifications:
  email: false
