language: go
go:
    - stable
    - master
matrix:
  allow_failures:
    - go: master

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq mpd mpc
install:
    - go get -u github.com/golang/lint/golint
    - ./just install

before_script:
    - sudo cp -r $TRAVIS_BUILD_DIR/testdata $(sudo sed -n 's/^music_directory\s\+"\(.\+\)"/\1/p' /etc/mpd.conf)
    - echo -e '\n
        max_connections "100"\n
        audio_output {\n
            type "null"\n
            name "My Null Output"\n
            mixer_type "software"\n
        }' | sudo tee -a /etc/mpd.conf
    - sudo service mpd restart
    - mpc update --wait
script:
    - gofmt -s -d ./src/
    - ./just build
    - RELEASE=1 ./just build
    - go test -test.v -race ./src/...
    - go vet ./src/...
    - golint -set_exit_status -min_confidence 0.3 ./src/...
