# The network address to listen on. Must be in the Go listen format.
#
# Example, listen on port 80 on all interfaces:
#  :80
bind: 127.0.0.1:3000

# The base URL at which the webinterface will can be reached by clients.
# Must end with '/'.
url_root: http://localhost:3000/

# The directory which Trollibox will use to store data which can not be
# saved to configured players.
storage_dir: ~/.config/trollibox

# The CSS colors used in the interface.
colors:
  background: "#333"
  background_elem: "#222"
  text: "#eee"
  text_inactive: "#aaa"
  accent: "#f60"

# Sets the default player by name. Leave empty to let Trollibox select a
# random player.
default_player:

# The sections below list options to configure the players that Trollibox
# will control. Each player is identified by a unique "name" property.

# MPD instances to control. Leave emtpy if you don't want to configure any
# MPD instances.
mpd:
  - name: space
    network: tcp
    address: 127.0.0.1:6600
    password:

# Logitech SlimServer to control. Set to null if you don't want to configure a
# SlimServer. The players along with their names are automatically detected.
slimserver:
  network: tcp
  address: 127.0.0.1:9090
  username:
  password:

  # The root of the SlimServer's web interface. Used to query track art.
  weburl: http://127.0.0.1:9000/
