required = [
  "github.com/tdewolff/minify",
  "github.com/tmthrgd/go-bindata",
]

[[constraint]]
  name = "github.com/fhs/gompd"
  version = "2.0.2"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.3"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "golang.org/x/net"
  branch = "release-branch.go1.11"
