required = [
  "github.com/tdewolff/minify",
  "github.com/tmthrgd/go-bindata",
]

[[constraint]]
  name = "github.com/fhs/gompd"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/mux"
  branch = "master"

[[constraint]]
  branch = "release-branch.go1.8"
  name = "golang.org/x/net"
