#! /bin/sh
### BEGIN INIT INFO
# Provides:          trollibox
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts trollibox
### END INIT INFO

#
# Trollibox
#
# The Trollibox Authors
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/trollibox
CONFIG=/etc/trollibox/config.json
PID=/var/run/trollibox.pid
NAME=trollibox

test -x $DAEMON || exit 1

# Change this stuff or create the user.
USERID=trollibox
GROUPID=trollibox
ENABLE="true"

if [ "$ENABLE" != "true" ]; then
	echo "$NAME daemon disabled"
	exit 0
fi

set -e

start_trollibox() {
	start-stop-daemon --start --background --quiet --pidfile $PID --chuid $USERID:$GROUPID --exec $DAEMON -- -conf $CONFIG
}

stop_trollibox() {
	# Send TERM after 5 seconds, wait at most 30 seconds.
	start-stop-daemon --stop --oknodo --retry TERM/5/0/30 --quiet --pidfile $PID --exec $DAEMON
}

case "$1" in
	start)
		echo "Starting $NAME"
		start_trollibox
		;;
	stop)
		echo "Stopping $NAME"
		stop_trollibox
		;;
	reload|force-reload)
		echo "Reloading $NAME"
		start-stop-daemon --stop --signal 1 --quiet --exec $DAEMON
		;;
	restart)
		echo "Restarting $NAME"
		start_trollibox
		stop_trollibox
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload|force-reload}" >&2
		exit 1
		;;
esac

exit 0
