name: Bump

on:
  workflow_dispatch:

jobs:

  test:
    uses: ./.github/workflows/test.yml

  bump:
    runs-on: ubuntu-latest
    container:
      image: codeberg.org/polyfloyd/nix-ci:latest

    needs:
      - test

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ssh-key: "${{ secrets.DEPLOY_SSH_KEY }}"
    - name: Populate /nix/store
      run: echo done

    - name: Git Identity
      run: |
        git config --local user.email "github-actions@users.noreply.github.com"
        git config --local user.name "github-actions"

    - run: cz bump --changelog

    - run: git push
    - run: git push --tags
