name: Release

on:
  push:
    tags:
    - 'v*'

defaults:
  run:
    shell: nix develop --command {0}

permissions:
  contents: write

jobs:

  release:
    runs-on: ubuntu-latest
    container:
      image: codeberg.org/polyfloyd/nix-ci:latest

    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2

  build:
    runs-on: ubuntu-latest
    container:
      image: codeberg.org/polyfloyd/nix-ci:latest

    needs:
      - release
    strategy:
      fail-fast: false
      matrix:
        arch:
        - aarch64
        - x86_64
        os:
        - unknown-linux-gnu
        include:
        - os: unknown-linux-gnu
          goos: linux
        - arch: aarch64
          goarch: arm64
        - arch: x86_64
          goarch: amd64

    steps:
    - uses: actions/checkout@v4
    - name: Populate /nix/store
      run: echo done

    - run: make
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}

    - run: tar -czf trollibox-${{ matrix.arch }}-${{ matrix.os}}.tar.gz -C ./bin trollibox ../config.example.yaml

    - name: Upload binary to release
      uses: softprops/action-gh-release@v2
      with:
        files: trollibox-${{ matrix.arch }}-${{ matrix.os}}.tar.gz
