name: Release

on:
  push:
    tags:
    - 'v*'

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

  build:
    strategy:
      fail-fast: false
      matrix:
        target:
        - linux-amd64
        - linux-arm6
        - linux-arm7
        - linux-arm64
        include:
        - target: linux-amd64
          goarch: amd64
          goos: linux
        - target: linux-arm6
          goarch: arm
          goos: linux
          goarm: 6
        - target: linux-arm7
          goarch: arm
          goos: linux
          goarm: 7
        - target: linux-arm64
          goarch: arm64
          goos: linux

    needs:
    - release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: stable
    - uses: actions/setup-node@v4
      with:
        node-version: 17

    - run: make
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        GOARM: ${{ matrix.goarm }}
    - run: tar -czf trollibox-${{ matrix.target }}.tar.gz -C ./bin trollibox ../config.example.yaml

    - name: Upload binary to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: trollibox-${{ matrix.target }}.tar.gz
        tag: ${{ github.ref }}
