name: Release

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2

  build:
    strategy:
      fail-fast: false
      matrix:
        arch:
        - aarch64
        - x86_64
        os:
        - unknown-linux-gnu
        - unknown-linux-musl
        include:
        - os: unknown-linux-gnu
          goos: linux
        - os: unknown-linux-musl
          goos: linux
        - arch: aarch64
          goarch: arm64
        - arch: x86_64
          goarch: amd64

    needs:
    - release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - uses: actions/setup-node@v4
      with:
        node-version: 17

    - uses: jirutka/setup-alpine@v1
      if: matrix.os == 'unknown-linux-musl'
      with:
        branch: v3.21
        packages: >
          go

    - run: make
      if: matrix.os != 'unknown-linux-musl'
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      shell: alpine.sh {0}

    - run: make
      if: matrix.os == 'unknown-linux-musl'
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}

    - run: tar -czf trollibox-${{ matrix.arch }}-${{ matrix.os}}.tar.gz -C ./bin trollibox ../config.example.yaml

    - name: Upload binary to release
      uses: softprops/action-gh-release@v2
      with:
        files: trollibox-${{ matrix.arch }}-${{ matrix.os}}.tar.gz
