name: Release

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2

  build:
    strategy:
      fail-fast: false
      matrix:
        arch:
        - aarch64
        - x86_64
        os:
        - unknown-linux-gnu
        include:
        - os: unknown-linux-gnu
          goos: linux
        - arch: aarch64
          goarch: arm64
        - arch: x86_64
          goarch: amd64

    needs:
    - release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - uses: actions/setup-node@v4
      with:
        node-version: 17

    - run: make
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}

    - run: tar -czf trollibox-${{ matrix.arch }}-${{ matrix.os}}.tar.gz -C ./bin trollibox ../config.example.yaml

    - name: Upload binary to release
      uses: softprops/action-gh-release@v2
      with:
        files: trollibox-${{ matrix.arch }}-${{ matrix.os}}.tar.gz
